### ISSUE TITLE
原理是什么呢？

### ISSUE THREAD

**Issue by zhiting9420** [wsc0615/aDriveFileShare#1]
添加一个视频文件 修改了md5吗？ 然后再加上后缀 
有一个小小的建议就是修改过后的文件把二级后缀去掉改成.MP4 这样肉眼也能迷惑 修改过后的文件加上一点特定的字符好分辨出这个是伪装过的(文件太多容易分不清)

**Comment by wsc0615** [comment]
这个小工具是为了紧急分享一个文件而临时写的，如果用的人多，需求量大的话，可以考虑再继续优化下。原理其实很简单，修改了文件的头部属性，md5肯定也会被修改的

**Comment by wsc0615** [comment]
> 添加一个视频文件 修改了md5吗？ 然后再加上后缀 有一个小小的建议就是修改过后的文件把二级后缀去掉改成.MP4 这样肉眼也能迷惑 修改过后的文件加上一点特定的字符好分辨出这个是伪装过的(文件太多容易分不清)

这个小工具是为了紧急分享一个文件而临时写的，如果用的人多，需求量大的话，可以考虑再继续优化下。原理其实很简单，修改了文件的头部属性，md5肯定也会被修改的
